apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-svc
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: erog-app
  type: LoadBalancer
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-app-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: nodejs-demo.wohlig.com
    http:
      paths:
        - pathType: Prefix
          backend:
            service:
              name: nodejs-app-svc
              port:
                number: 80
          path: /
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deploy
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: 1020636/nodejs:v4-20240115063613
        ports:
        - containerPort: 3000
